Repository endatix/endatix, pull requests merged in 2024-08, with the labels that each got.

#61 docs: Updated product description in readme.
  README.md
Labels: documentation

#63 docs: Add MIT LICENSE
  LICENSE
Labels: documentation, enhancement

#69 refactor: Refactor solution architecture to be used as library #52
  .vscode/launch.json
  Endatix.sln
  src/Endatix.Api/Endatix.Api.csproj
  src/Endatix.Api/Infrastructure/MediatRServiceConfigExtensions.cs
  src/Endatix.Api/Infrastructure/ResultExtensions.cs
  src/Endatix.Api/Program.cs
  src/Endatix.Api/Setup/EndatixAppExtensions.cs
  src/Endatix.Api/Setup/MiddlewareExtensions.cs
  src/Endatix.Core/Configuration/EndatixConfig.cs
  src/Endatix.Core/Configuration/EndatixConfigExtensions.cs
  src/Endatix.Core/Events/SubmissionCompletedEvent.cs
  src/Endatix.Core/Handlers/SubmissionCompletedHandler.cs
  src/Endatix.Extensions.Hosting/AppBuilderExtensions.cs
  src/Endatix.Extensions.Hosting/Endatix.Extensions.Hosting.csproj
  src/Endatix.Extensions.Hosting/EndatixMiddleware.cs
  src/Endatix.Extensions.Hosting/EndatixWebApp.cs
  src/Endatix.Extensions.Hosting/EndatixWebAppBuilderExtensions.cs
  src/Endatix.Framework/Endatix.Framework.csproj
  src/Endatix.Framework/Hosting/IEndatixApp.cs
  src/Endatix.Framework/Hosting/IEndatixMiddleware.cs
  src/Endatix.Infrastructure/Endatix.Infrastructure.csproj
  src/Endatix.Infrastructure/Setup/ConfigurationOptions.cs
  src/Endatix.Infrastructure/Setup/EndatixAppExtensions.cs
  src/Endatix.Infrastructure/Setup/MediatRConfigOptions.cs
  src/Endatix.Infrastructure/Setup/ServiceCollectionExtensions.cs
  src/Endatix.SqlServer/ServiceCollectionExtensions.cs
  src/Endatix.SqlServer/Setup/EndatixAppExtensions.cs
  src/Endatix.WebHost/Endatix.WebHost.csproj
  src/Endatix.WebHost/Program.cs
  src/Endatix.WebHost/Properties/launchSettings.json
  src/Endatix.WebHost/appsettings.Development.json
  src/Endatix.WebHost/appsettings.json
Labels: :triangular_ruler: architecture

#73 feat: Package and configure Endatix NuGet packages
  .gitignore
  Directory.Build.props
  build/endatix-icon.png
  samples/Endatix.Samples.CustomEventHandlers/Endatix.Samples.CustomEventHandlers.csproj
  samples/Endatix.Samples.WebApp/Endatix.Samples.WebApp.csproj
  src/Endatix.Api.Host/Endatix.Api.Host.csproj
  src/Endatix.Api.Host/README.md
  src/Endatix.Api/Endatix.Api.csproj
  src/Endatix.Api/README.md
  src/Endatix.Core/Endatix.Core.csproj
  src/Endatix.Core/README.md
  src/Endatix.Extensions.Hosting/Endatix.Extensions.Hosting.csproj
  src/Endatix.Extensions.Hosting/README.md
  src/Endatix.Framework/Endatix.Framework.csproj
  src/Endatix.Framework/README.md
  src/Endatix.Infrastructure/Endatix.Infrastructure.csproj
  src/Endatix.Infrastructure/README.md
  src/Endatix.SqlServer/Endatix.SqlServer.csproj
  src/Endatix.SqlServer/README.md
  src/Endatix.WebHost/README.md
Labels: enhancement
